server:
  port: 7529
  servlet:
    # 将Servlet的上下文路径配置为“/api”，那么应用的根路径就变成了“http://localhost:7529/api/”。
    context-path: /api
spring:
  application:
    name: base-demo
  # 数据库配置
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/chenmeng_test
    username: root
    password: 123456
  mvc:
    pathmatch:
      # 指定URL路径匹配的策略--Ant--风格，默认的URL路径匹配的策略是AntPathMatcher
      # 是为了兼容swagger
      matching-strategy: ANT_PATH_MATCHER
# mybatis-plus配置
mybatis-plus:
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID", 3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: AUTO
      #字段策略 -- 例如利用updateWrapper更新时，会做null判断，如果传参数为null，就不会更新
      insert-strategy: not_null
      update-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      #逻辑删除配置
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    # 打印日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false