# mybatis-plus配置
mybatis-plus:
  configuration:
    # 打印日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  cloud:
    stream:
      # stream + kafka 配置
      kafka:
        binder:
          brokers: 127.0.0.1:9092 #Kafka的消息中间件服务器
          auto-create-topics: true #设置自动创建Topic
      bindings:
        output:
          destination: demo_topic #消息发往的目的地
          content-type: text/plain #消息发送的格式，这里使用 text。发送字符串消息的时候需要配置，默认是 json格式
        input:
          destination: demo_topic #目的地
          group: demo_consumer_group #消费者分组
        # 自定义output - 生产
        face_output:
          destination: face_topic
          content-type: text/plain
        human_output:
          destination: human_topic
          content-type: application/json #默认是 application/json（可能会因版本而异）
        vehicle_output:
          destination: vehicle_topic
        # 自定义input - 消费
        face_input:
          destination: face_topic
          group: face_consumer_group
        human_input:
          destination: human_topic
          group: human_consumer_group
        vehicle_input:
          destination: vehicle_topic
          group: vehicle_consumer_group